# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: IUTQCMBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: default_security_target
                use_referer: true
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

            #Pour se logout
            logout:
                path:   /logout
                target: /
    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/profile, role: ROLE_USER }
            - { path: /add, role: ROLE_PROF }

            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        IUT\QCMBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
    #Les Variables doivent commencer par "ROLE_"
        ROLE_ADMIN: [ROLE_PROF, ROLE_ELEVE, ROLE_USER]  #ROLE_ALLOWED_TO_SWITCH  #Role de l'admin
        ROLE_PROF :  ROLE_USER #Role du prof
        ROLE_ELEVE : ROLE_USER #Role de l'élève
        ROLE_USER : #ROLE CONNECTÉ